# ...
on:
    push
jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: [3.9]

        env:
            USING_COVERAGE: "3.9"

        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install black coverage flake8 flit mccabe mypy pylint pytest tox tox-gh-actions pillow

            - name: Run tox
              run: |
                  python -m tox

            - name: Convert coverage files to JSON
              run: |
                  python -m coverage json -i
                  dir

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              if: contains(env.USING_COVERAGE, matrix.python-version)
              with:
                  fail_ci_if_error: true
                  functionalities:
                    coveragepy

            - name: List all files in directory
              run: |
                  dir

            - name: Upload raw coverage as artifact
              uses: actions/upload-artifact@v2
              with:
                name: .coverage
                path: .coverage
                retention-days: 5

            - name: Upload XML coverage as artifact
              uses: actions/upload-artifact@v2
              with:
                name: coverage.xml
                path: coverage.xml
                retention-days: 5
